name: derrickritch
favicon: null
layout_spectrum: 0.0003688451834022999
typography_spectrum: 0.8351553783286363
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75791708-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6471925608348101
  lightness: 0.9983723689801991
  saturation: 0.7406337347347289
  rhythmicContrast: 0.8534562026616186
purpose: []
